/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finca_ganadera;


import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Comprar_ganado extends javax.swing.JFrame {
    
    /**
     * Creates new form Comprar_ganado
     */
    public Comprar_ganado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_potrero = new javax.swing.JTextField();
        t_raza = new javax.swing.JTextField();
        t_cantidad = new javax.swing.JTextField();
        b_volver = new javax.swing.JButton();
        b_comprar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setPreferredSize(new java.awt.Dimension(730, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto.setBackground(new java.awt.Color(204, 204, 204));
        texto.setFont(new java.awt.Font("Sitka Banner", 1, 48)); // NOI18N
        texto.setForeground(new java.awt.Color(51, 51, 51));
        texto.setText("COMPRAR GANADO");
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 400, 80));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel2.setText("Raza:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel1.setText("Numero de potrero");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel3.setText("Cantidad de ganado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));
        getContentPane().add(t_potrero, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 120, 20));
        getContentPane().add(t_raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 120, 20));
        getContentPane().add(t_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 120, -1));

        b_volver.setBackground(new java.awt.Color(153, 204, 255));
        b_volver.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        b_volver.setText("Volver al menú principal");
        b_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });
        getContentPane().add(b_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        b_comprar.setBackground(new java.awt.Color(153, 153, 255));
        b_comprar.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        b_comprar.setText("COMPRAR");
        b_comprar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_comprarActionPerformed(evt);
            }
        });
        getContentPane().add(b_comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 110, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprar2.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-430, -60, 1280, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Pagina_principal a = new Pagina_principal();
        a.setVisible(true);
    }//GEN-LAST:event_b_volverActionPerformed

    private void b_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_comprarActionPerformed
        // TODO add your handling code here:        
        int potrero = Integer.parseInt(t_potrero.getText());
        int cantidad = Integer.parseInt(t_cantidad.getText());
        String raza = String.valueOf(t_raza.getText());
        JOptionPane.showMessageDialog(null, "potrero: " + potrero);
        JOptionPane.showMessageDialog(null, "raza: " + raza);
        JOptionPane.showMessageDialog(null, "cantidad animales: " + cantidad);
        int peso;
        int suma = 0;
        
        for (int i = 0; i < cantidad; i++) {
            peso = (int)(Math.random()*(600-400)+400);
            suma += peso;
        }
            
            if (suma>6000){
                JOptionPane.showMessageDialog(null,"Hay demasiado peso, no puedes comprar todo mi rey");
            }else{
                JOptionPane.showMessageDialog(null,"compra exitosa");
            }
            JOptionPane.showMessageDialog(null, "suma de los pesos del ganado: " + suma + " Kilogramos");
        
        
        
    
    }//GEN-LAST:event_b_comprarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprar_ganado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_comprar;
    private javax.swing.JButton b_volver;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField t_cantidad;
    private javax.swing.JTextField t_potrero;
    private javax.swing.JTextField t_raza;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
