/*
Mover ganado 
generar codigo del ganado y si están vacunados o no 
controlar vacunación 
agregar ganado a potreros adicionales
Ver animales en cada potrero 
Ventas animales 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finca_ganadera;

import java.util.Arrays;
import java.util.HashSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class Pagina_principal extends javax.swing.JFrame {

    /**
     * Creates new form Control_ganado
     */
    static String potrero1[]=new String [80];
    static String potrero2[]=new String [80];
    static String potrero3[]=new String [80];
    static String potrero4[]=new String [80];
    static String potrero5[]=new String [60];
    static String potrero6[]=new String [60];
    static String potrero7[]=new String [60];
    static String potrero8[]=new String [60];
    static String p_ventas[]=new String [40];
    public Pagina_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_mover1 = new javax.swing.JButton();
        b_comprar = new javax.swing.JButton();
        b_salir = new javax.swing.JButton();
        b_vacunar = new javax.swing.JButton();
        titulo1 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_mover1.setBackground(new java.awt.Color(204, 204, 255));
        b_mover1.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        b_mover1.setText("Mover Ganado");
        b_mover1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_mover1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_mover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_mover1ActionPerformed(evt);
            }
        });
        getContentPane().add(b_mover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 150, 30));

        b_comprar.setBackground(new java.awt.Color(204, 204, 255));
        b_comprar.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        b_comprar.setText("Comprar ganado");
        b_comprar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_comprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_comprarActionPerformed(evt);
            }
        });
        getContentPane().add(b_comprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 30));

        b_salir.setBackground(new java.awt.Color(204, 204, 255));
        b_salir.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        b_salir.setText("Salir");
        b_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });
        getContentPane().add(b_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 150, 30));

        b_vacunar.setBackground(new java.awt.Color(204, 204, 255));
        b_vacunar.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        b_vacunar.setText("Vacunar ganado");
        b_vacunar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_vacunar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_vacunarActionPerformed(evt);
            }
        });
        getContentPane().add(b_vacunar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 150, 30));

        titulo1.setFont(new java.awt.Font("Sitka Banner", 0, 36)); // NOI18N
        titulo1.setText("BIENVENIDO A NUESTRA GRANJA");
        getContentPane().add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 500, 40));

        texto1.setFont(new java.awt.Font("Sitka Banner", 0, 30)); // NOI18N
        texto1.setText("más que una granja, somos una familia");
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_mover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_mover1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Mover_ganado a = new Mover_ganado();
        a.setVisible(true);
    }//GEN-LAST:event_b_mover1ActionPerformed

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_b_salirActionPerformed

    private void b_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_comprarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Comprar_ganado e = new Comprar_ganado();
        e.setVisible(true);
        
    }//GEN-LAST:event_b_comprarActionPerformed

    private void b_vacunarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_vacunarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Vacunar_ganado a = new Vacunar_ganado();
        a.setVisible(true);
    }//GEN-LAST:event_b_vacunarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        int codigo;
        int vacunado;
        for (int i = 0; i < 30; i++) {
            codigo=(int)(Math.random()*(500-100)+100);
            
            potrero1[i]="R1 - "+String.valueOf(codigo);
            potrero1[i+30]="R3 - "+String.valueOf(codigo);
            
        }
         for (int i = 0; i < 40; i++) {
            codigo=(int)(Math.random()*(500-100)+100);
            potrero2[i]="R2 - "+String.valueOf(codigo);
            if(i+40<70){
               potrero2[i+40]="R4 - "+String.valueOf(codigo);
              if(i+40==70)i=40; 
            }    
        }
          for (int i = 0; i < 30; i++) {
            codigo=(int)(Math.random()*(500-100)+100);
            potrero3[i]="R1 - "+String.valueOf(codigo);
            if(i+30<50){
               potrero3[i+30]="R5 - "+String.valueOf(codigo);
              if(i+30==50)i=40; 
            }    
        }
          for (int i = 0; i < 40; i++) {
            codigo=(int)(Math.random()*(500-100)+100);
            potrero4[i]="R4 - "+String.valueOf(codigo);
            if(i+40<70){
               potrero4[i+40]="R6 - "+String.valueOf(codigo);
              if(i+40==70)i=40; 
            }    
        }
          for (int i = 0; i < 80; i++) {
              vacunado=(int)(Math.random()*2);
            if(vacunado==1 && potrero1[i]!=null){
                potrero1[i]+="/Si";
            }
            else if(vacunado==0 && potrero1[i]!=null) {
                potrero1[i]+="/No";
            }
            vacunado=(int)(Math.random()*2);
            if(vacunado==1 && potrero2[i]!=null){
                potrero2[i]+="/Si";
            }
            else if(vacunado==0 && potrero2[i]!=null) {
                potrero2[i]+="/No";
            }
            vacunado=(int)(Math.random()*2);
            if(vacunado==1 && potrero3[i]!=null){
                potrero3[i]+="/Si";
            }
            else if(vacunado==0 && potrero3[i]!=null) {
                potrero3[i]+="/No";
            }
            vacunado=(int)(Math.random()*2);
            if(vacunado==1 && potrero4[i]!=null){
                potrero4[i]+="/Si";
            }
            else if(vacunado==0 && potrero4[i]!=null) {
                potrero4[i]+="/No";
            }
        }
          
                         
          
        /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagina_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagina_principal().setVisible(true);
            }
        });
    }

      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_comprar;
    private javax.swing.JButton b_mover1;
    private javax.swing.JButton b_salir;
    private javax.swing.JButton b_vacunar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
