/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finca_ganadera;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Vacunar_ganado extends javax.swing.JFrame {

    /**
     * Creates new form Vacunar_ganado
     */
    public Vacunar_ganado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_volver = new javax.swing.JButton();
        t_potrero_vacunar = new javax.swing.JTextField();
        t_nro_vacunas = new javax.swing.JTextField();
        b_vacunar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setPreferredSize(new java.awt.Dimension(730, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_volver.setBackground(new java.awt.Color(153, 204, 255));
        b_volver.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        b_volver.setText("Volver al menú principal");
        b_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });
        getContentPane().add(b_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));
        getContentPane().add(t_potrero_vacunar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 130, -1));

        t_nro_vacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nro_vacunasActionPerformed(evt);
            }
        });
        getContentPane().add(t_nro_vacunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 130, -1));

        b_vacunar.setBackground(new java.awt.Color(204, 153, 255));
        b_vacunar.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        b_vacunar.setText("VACUNAR");
        b_vacunar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_vacunar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_vacunarActionPerformed(evt);
            }
        });
        getContentPane().add(b_vacunar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 120, 30));

        jLabel2.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elige un potreo a vacunar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 200, 40));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese la cantidad de ganado a vacunar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vacunar Ganado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 240, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_vacunar.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-360, -90, 1240, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Pagina_principal a = new Pagina_principal();
        a.setVisible(true);
    }//GEN-LAST:event_b_volverActionPerformed

    private void t_nro_vacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nro_vacunasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_t_nro_vacunasActionPerformed

    private void b_vacunarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_vacunarActionPerformed
        // TODO add your handling code here:
        int potrero = Integer.parseInt(t_potrero_vacunar.getText());
        int cantidad = Integer.parseInt(t_nro_vacunas.getText());
        JOptionPane.showMessageDialog(null, "potrero " + potrero);
        JOptionPane.showMessageDialog(null, "cantidad a vacunar: " + cantidad);
        
    }//GEN-LAST:event_b_vacunarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vacunar_ganado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vacunar_ganado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vacunar_ganado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vacunar_ganado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vacunar_ganado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_vacunar;
    private javax.swing.JButton b_volver;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField t_nro_vacunas;
    private javax.swing.JTextField t_potrero_vacunar;
    // End of variables declaration//GEN-END:variables
}
